# Generated by Django 5.0 on 2026-01-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="report_reason",
            field=models.CharField(default="1", max_length=255),
            preserve_default=False,
        ),
    ]
